vm_start:
  description: Start a virtual machine
  fields:
    entity_id:
      description: Sensor entity id for virtual machine
      example: "binary_sensor.virtural_machine_name"
    overcommit:
      description: Start the virtual machine even if there is not enough memory available
      example: False

vm_stop:
  description: Stop a virtual machine
  fields:
    entity_id:
      description: Sensor entity id for virtual machine
      example: "binary_sensor.virtural_machine_name"
    force:
      description: Perform a non-graceful shutdown
      example: False

vm_restart:
  description: Restart a virtual machine
  fields:
    entity_id:
      description: Sensor entity id for virtual machine
      example: "binary_sensor.virtural_machine_name"
